spring.application.name=AvanceProyecto

# ==================== MySQL Configuration ====================
spring.datasource.url=jdbc:mysql://localhost:3306/ConsultorioDB?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Caramelito

# ==================== JPA / Hibernate ====================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true