spring.application.name=AvanceProyecto

# ==================== MySQL Configuration ====================
spring.datasource.url=jdbc:mysql://mysql-3bda589e-lujanenrique37-9b74.a.aivencloud.com:14999/consultoriodb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver


# ==================== JPA / Hibernate ====================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==================== JWT Configuration ====================
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
